language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - LARAVEL=5.8.*
    - LARAVEL=dev-master

matrix:
  exclude:
    - php: 7.1
      env: LARAVEL=dev-master
  allow_failures:
    - env: LARAVEL=dev-master

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update

install:
  - travis_retry composer require "illuminate/support=${LARAVEL}" --dev --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit --verbose
